# Generated by Django 4.2.16 on 2025-01-14 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="subscription",
            options={
                "permissions": [
                    ("advanced", "Advanced Perm"),
                    ("pro", "Pro Perm"),
                    ("basic", "Basic Perm"),
                    ("basic_ai", "Basic_AI Perm"),
                ]
            },
        ),
    ]
