# Generated by Django 5.0.11 on 2025-02-27 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0009_subscriptionprice"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="subscriptionprice",
            options={},
        ),
        migrations.AddField(
            model_name="subscriptionprice",
            name="featured",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="subscriptionprice",
            name="order",
            field=models.IntegerField(default=-1),
        ),
    ]
