# Generated by Django 5.0.11 on 2025-02-27 13:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0010_alter_subscriptionprice_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscriptionprice",
            name="timestamp",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="subscriptionprice",
            name="updated",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="subscriptionprice",
            name="featured",
            field=models.BooleanField(
                default=True, help_text="Featured on the Django Pricing Page"
            ),
        ),
        migrations.AlterField(
            model_name="subscriptionprice",
            name="order",
            field=models.IntegerField(
                default=-1, help_text="Ordering on Django Price page"
            ),
        ),
    ]
