# Generated by Django 5.0.11 on 2025-04-20 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0020_usersubscription_status"),
    ]

    operations = [
        migrations.RenameField(
            model_name="usersubscription",
            old_name="Subscription",
            new_name="subscription",
        ),
    ]
