# Generated by Django 5.0.11 on 2025-04-20 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0021_rename_subscription_usersubscription_subscription"),
    ]

    operations = [
        migrations.RenameField(
            model_name="usersubscription",
            old_name="subscription",
            new_name="Subscription",
        ),
    ]
