# Generated by Django 5.0.11 on 2025-04-20 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0023_usersubscription_cancel_at_period_end"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usersubscription",
            name="cancel_at_period_end",
            field=models.BooleanField(default=True),
        ),
    ]
